server: 
  port: 8080 
  error:
    include-stacktrace: never 
spring: 
  application:
    name: Edicola 
  datasource: 
    
    url: jdbc:mysql://localhost:3306/club_tennis
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa: 
    hibernate:
      
    database-platform: org.hibernate.dialect.MySQLDialect
    
    show-sql: true
    
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    deserialization:
      fail-on-unknown-properties: true
